#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"

#include "trans/push.h"
#include "trans/call.h"
#include "trans/test.h"
#include "trans/je.h"
#include "trans/pop.h"
#include "trans/ret.h"
#include "trans/add.h"
#include "trans/cmp.h"
#include "trans/sub.h"
#include "trans/sbb.h"
#include "trans/jmp.h"
#include "trans/jbe.h"
#include "trans/jle.h"
#include "trans/jl.h"
#include "trans/ja.h"
#include "trans/jg.h"
#include "trans/js.h"
#include "trans/jns.h"
#include "trans/jge.h"
#include "trans/clt.h"
#include "trans/jne.h"
#include "trans/leave.h"
#include "trans/lea.h"
#include "trans/adc.h"
#include "trans/movzb.h"
#include "trans/movzw.h"
#include "trans/cmovs.h"
#include "trans/movsb.h"
#include "trans/movsw.h"
#include "trans/movs.h"
#include "trans/setne.h"
#include "trans/nop.h"
#include "trans/lods.h"
#include "trans/scas.h"
#include "trans/stos.h"
#include "trans/lgdt.h"
#include "trans/std.h"
#include "trans/cld.h"

